tasks:
  - name: Backend Setup
    init: cd backend && stack build
    command: cd backend && stack run

  - name: Frontend Setup
    init: cd frontend && npm install
    command: cd frontend && npm start

ports:
  - port: 3000
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - haskell.haskell
    - dbaeumer.vscode-eslint
