services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/thrift_crowd_staking
      - BLOCKFROST_PROJECT_ID=${BLOCKFROST_PROJECT_ID}
      - BLOCKFROST_BASE_URL=https://cardano-preprod.blockfrost.io/api/v0
      - CARDANO_NETWORK=preprod
      - CARDANO_WALLET_ADDRESS=${CARDANO_WALLET_ADDRESS}
      - CARDANO_WALLET_SKEY_FILE=/app/keys/wallet.skey
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.yaml:/app/package.yaml
      - ./backend/stack.yaml:/app/stack.yaml
      - ./keys:/app/keys:ro
    # Use the compiled binary from Dockerfile
    command: thrift-crowd-staking-exe
    develop:
      watch:
        - action: rebuild
          path: ./backend/package.yaml
        - action: rebuild  
          path: ./backend/stack.yaml
        - action: sync
          path: ./backend/src
          target: /app/src

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=thrift_crowd_staking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
