name: thrift-crowd-staking
version: 0.1.0.0
github: "Josiah-O/thrift-crowd-staking"
license: BSD3
author: "Josiah"
maintainer: "buildwithjosiah@gmail.com"
copyright: "2025 Josiah"

description: Please see the README on GitHub at <https://github.com/Josiah-O/thrift-crowd-staking#readme>

dependencies:
- base >= 4.7 && < 5
- text
- aeson
- servant-server
- wai
- warp
- postgresql-simple
- mtl
- time
- hashable
- uuid
- http-client
- http-client-tls
- http-types
- bytestring
- http-api-data
- process

library:
  source-dirs: src

executables:
  thrift-crowd-staking-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thrift-crowd-staking

# tests:
#   thrift-crowd-staking-test:
#     main: Spec.hs
#     source-dirs: test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - thrift-crowd-staking
