resolver: lts-21.22

packages:
- .
- ../smart-contracts

# Remove problematic git-based crypto dependencies
# Use official packages from Stackage instead
extra-deps:
# Only include essential Plutus dependencies
- git: https://github.com/IntersectMBO/plutus
  commit: 75267027f157f1312964e7126280920d1245c52d
  subdirs:
    - plutus-core
    - plutus-ledger-api
    - plutus-tx
    - plutus-tx-plugin

allow-newer: true

# Remove problematic crypto flags
# flags:
#   cardano-crypto-class:
#     secp256k1-support: true
