resolver: lts-21.22

packages:
- .
- ../smart-contracts

extra-deps:
- servant-0.19.1
- servant-server-0.19.2

allow-newer: true


allow-newer: true

flags:
  cardano-crypto-class:
    secp256k1-support: true
