resolver: lts-21.22

packages:
- .
- ../smart-contracts

# Simplified dependencies - use only essential Plutus packages
extra-deps:
# Plutus dependencies only
- git: https://github.com/IntersectMBO/plutus
  commit: 75267027f157f1312964e7126280920d1245c52d
  subdirs:
    - plutus-core
    - plutus-ledger-api
    - plutus-tx
    - plutus-tx-plugin
    - prettyprinter-configurable

# Remove problematic cardano-base git dependency
# Let Stack resolve these from Stackage/Hackage

allow-newer: true

# Remove problematic crypto flags
# flags:
#   cardano-crypto-class:
#     secp256k1-support: true
