resolver: lts-21.22

packages:
- .
- ../smart-contracts

extra-deps:
# Git-based dependencies needed for smart-contracts package in workspace
- git: https://github.com/IntersectMBO/plutus
  commit: 75267027f157f1312964e7126280920d1245c52d
  subdirs:
    - plutus-core
    - plutus-ledger-api
    - plutus-tx
    - plutus-tx-plugin
    - prettyprinter-configurable
# Try using just one cardano-base repo
- git: https://github.com/IntersectMBO/cardano-base
  commit: f11ddc7f87038c16d5a6d7611fb5dda51be9533d
  subdirs:
    - cardano-binary
    - cardano-crypto-class
    - heapwords
    - cardano-strict-containers

allow-newer: true

flags:
  cardano-crypto-class:
    secp256k1-support: true
